- name: Deploy stack
  hosts: all
  become: yes
  tasks:
    - name: Install Docker
      apt:
        name:
          - docker.io
          - python3-docker
    - name: Start Docker
      systemd:
        name: docker
        enabled: yes
        state: started
    - name: Create directories
      block:
        - name: Base directory
          file:
            state: directory
            path: /project
        - name: DB directory
          file:
            state: directory
            path: /project/db
        - name: Server directory
          file:
            state: directory
            path: /project/server
        - name: Certs directory
          file:
            state: directory
            path: /project/server/certs
    - name: Create cron job for nsupdate
      cron:
        name: nsupdate
        special_time: weekly
        job: "curl {{ nsupdate_url }}"
    - name: Login to Docker GH registry
      docker_login:
        registry_url: docker.pkg.github.com
        username: "{{ docker_username }}"
        password: "{{ docker_password }}"
    - name: Prune Docker leftovers
      docker_prune:
        images: yes
        containers: yes
    - name: Start MySQL container
      docker_container:
        name: db
        image: mysql:8
        cleanup: yes
        restart_policy: on-failure
        env:
          MYSQL_DATABASE: "{{ db_name }}"
          MYSQL_USER: "{{ db_user }}"
          MYSQL_PASSWORD: "{{ db_pass }}"
          MYSQL_RANDOM_ROOT_PASSWORD: "yes"
        volumes:
          - "/project/db:/var/lib/mysql"
    - name: Wait for database
      pause:
        seconds: 15
    - name: Start server container
      docker_container:
        name: server
        image: docker.pkg.github.com/projekt-zespolony/server/server:latest
        cleanup: yes
        recreate: yes
        pull: yes
        restart_policy: on-failure
        env:
          GOOGLE_APPLICATION_CREDENTIALS: "/firebase.json"
          SERVER_ACCESS_TOKEN: "{{ token }}"
          SERVER_PORT: "443"
          SERVER_CERTS_CACHE_DIR: /certs
          DB_NAME: "{{ db_name }}"
          DB_USER: "{{ db_user }}"
          DB_PASS: "{{ db_pass }}"
          DB_ADDR: db
        volumes:
          - "/project/server/firebase.json:/firebase.json:ro"
          - "/project/server/certs:/certs"
        ports:
          - 443:443
        links:
          - db
