- name: Deploy stack
  hosts: all
  become: yes
  tasks:
    - name: Install Docker
      apt:
        name:
          - docker.io
          - python3-docker
    - name: Start Docker
      systemd:
        name: docker
        enabled: yes
        state: started
    - name: Login to Docker GH registry
      docker_login:
        registry_url: docker.pkg.github.com
        username: "{{ docker_username }}"
        password: "{{ docker_password }}"
    - name: Start MySQL container
      docker_container:
        name: db
        image: mysql:8
        cleanup: yes
        restart_policy: on-failure
    - name: Start server container
      docker_container:
        name: server
        image: docker.pkg.github.com/projekt-zespolony/server/server:latest
        cleanup: yes
        recreate: yes
        pull: yes
        restart_policy: on-failure
        links:
          - db
