- name: Deploy
  hosts: all
  tasks:
    - name: Install Docker
      become: yes
      apt:
        name: docker.io
    - name: Start Docker
      become: yes
      systemd:
        name: docker
        enabled: yes
        state: started
    - name: Copy server binary
      become: yes
      copy:
        src: server
        dest: /usr/local/bin/server
        mode: '0755'
