name: CD

on:
  push:
    tags:
      - 'v*'

jobs:
  cd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Publish image
        uses: matootie/github-docker@v2.2.2
        with:
          accessToken: ${{github.token}}
          imageTag: latest
          buildArg: |
            VERSION=${{github.ref}}
            COMMIT=${{github.sha}}
      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v1
        with:
          playbook: deploy.yml
          key: ${{secrets.SSH_PRIVATE_KEY}}
          inventory: |
            [all]
            ${{secrets.SERVER_IP}} ansible_user=${{secrets.SERVER_USER}}
          options: |
            -e docker_username=${{github.actor}}
            -e docker_password=${{github.token}}
            -e server_access_token=${{secrets.SERVER_ACCESS_TOKEN}}
            -e db_name=${{secrets.DB_NAME}}
            -e db_user=${{secrets.DB_USER}}
            -e db_pass=${{secrets.DB_PASS}}
