name: CI

on: push

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.14
      - name: Build binary
        run: go build -v
      - name: Test code
        run: go test -v -count 3
      - name: Publish image
        if: github.event.ref == 'refs/heads/master'
        uses: matootie/github-docker@v2.2.2
        with:
          accessToken: ${{secrets.GITHUB_TOKEN}}
          imageTag: latest
      - name: Setup key
        if: github.event.ref == 'refs/heads/master'
        run: echo "${{secrets.SSH_PRIVATE_KEY}}" > key.pem
      - name: Run playbook
        if: github.event.ref == 'refs/heads/master'
        uses: saubermacherag/ansible-playbook-docker-action@v1.3
        with:
          playbookName: deploy.yml
          keyFile: key.pem
          extraVars: -i ${{secrets.SERVER_USER}}@${{secrets.SERVER_IP}},
