name: CI

on: push

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup
        uses: actions/setup-go@v1
        with:
          go-version: 1.14
      - name: Build
        run: go build -v
      - name: Test
        run: go test -v -count 3
      - name: Key
        if: github.event.ref == 'refs/heads/master'
        run: echo ${{secrets.SSH_PRIVATE_KEY}} > ssh_key.pem
      - name: Deploy
        if: github.event.ref == 'refs/heads/master'
        uses: saubermacherag/ansible-playbook-docker-action@v1.3
        with:
          playbookName: deploy.yml
          keyFile: ssh_key.pem
          extraVars: -i ${{secrets.SERVER_USER}}@${{secrets.SERVER_IP}},
