name: CI

on:
  push:
    paths:
      - '**.go'
      - 'go.*'
      - '.github/workflows/*'
      - 'Dockerfile'
      - 'docker-compose.yml'
      - 'postman.json'

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Compose up
        run: docker-compose up -d
      - name: Wait a bit
        run: sleep 10
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 13
      - name: Install newman
        run: npm install -g newman
      - name: Run newman
        run: newman run postman.json