name: CI

on:
  push:
    paths:
      - '**.go'
      - 'go.*'
      - '.github/workflows/*'
      - 'Dockerfile'
      - 'docker-compose.yml'
      - 'test.rb'

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2
      - name: Run tests
        run: ./test.rb