name: CI

on:
  push:
    paths:
      - '**.go'
      - 'go.*'
      - '.github/workflows/*'
      - 'Dockerfile'
      - 'docker-compose.yml'

env:
  HOST: localhost
  PORT: 8080
  VERSION: ${{github.ref}}
  COMMIT: ${{github.sha}}

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Compose build
        run: |
          docker-compose build \
            --build-arg VERSION=$VERSION \
            --build-arg COMMIT=$COMMIT
      - name: Compose up
        run: |
          docker-compose up -d
      - name: Wait for it
        run: |
          for try in $(seq 5); do
            sleep 5
            if curl -s $HOST:$PORT; then
              exit 0
            fi
          done
          exit 1
      - name: Test API /
        run: |
          curl -s $HOST:$PORT/ | jq -r .version | egrep "^$VERSION$"
          curl -s $HOST:$PORT/ | jq -r .commit | egrep "^$COMMIT$"
