name: Docs

on:
  push:
    branches:
      - master
    paths:
      - 'docs/**'
      - 'mkdocs.yml'

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.x
      - name: Install mkdocs
        run: pip install mkdocs mkdocs-material
      - name: Deploy docs
        run: mkdocs gh-deploy --verbose
